#!/bin/sh
# USB webcam gadget only. No dwc3 rebind. No ISP/pump (S99 starts those).
. /etc/profile

LOG=/userdata/cv-uvc-boot.log
log() { echo "$(cat /proc/uptime) $*" >> $LOG; }

uvc_rk() {
        : > $LOG
        log "uvc_rk start"
        mount -t configfs none /sys/kernel/config 2>/dev/null
        sleep 6

        G=/sys/kernel/config/usb_gadget/rockchip
        C=$G/configs/b.1
        U=$G/functions/uvc.gs1

        echo none > $G/UDC 2>/dev/null
        rm -f $C/f1 $C/f2 $C/f3 $C/f4 $C/ffs.adb 2>/dev/null

        mkdir -p $G/strings/0x409
        mkdir -p $C/strings/0x409
        echo 0x2207 > $G/idVendor
        echo 0x0016 > $G/idProduct
        echo 0x0310 > $G/bcdDevice
        echo 0x0200 > $G/bcdUSB
        echo 239 > $G/bDeviceClass
        echo 2 > $G/bDeviceSubClass
        echo 1 > $G/bDeviceProtocol
        echo CVSingle > $G/strings/0x409/serialnumber
        echo CameMake > $G/strings/0x409/manufacturer
        echo "CameVision Single" > $G/strings/0x409/product
        echo 500 > $C/MaxPower

        mkdir -p $U
        echo "CameVision Single" > $U/device_name
        echo "CameVision Single" > $U/function_name
        echo 3072 > $U/streaming_maxpacket
        echo 4 > $U/uvc_num_request
        echo 0 > $U/streaming_bulk 2>/dev/null

        mkdir -p $U/control/header/h
        [ -e $U/control/class/fs/h ] || ln -s $U/control/header/h $U/control/class/fs/h
        [ -e $U/control/class/ss/h ] || ln -s $U/control/header/h $U/control/class/ss/h

        mkdir -p $U/streaming/header/h
        mkdir -p $U/streaming/mjpeg/m/1920_1080p
        echo 1920 > $U/streaming/mjpeg/m/1920_1080p/wWidth
        echo 1080 > $U/streaming/mjpeg/m/1920_1080p/wHeight
        echo 666666 > $U/streaming/mjpeg/m/1920_1080p/dwDefaultFrameInterval
        echo 16000000 > $U/streaming/mjpeg/m/1920_1080p/dwMinBitRate
        echo 16000000 > $U/streaming/mjpeg/m/1920_1080p/dwMaxBitRate
        echo 3110400 > $U/streaming/mjpeg/m/1920_1080p/dwMaxVideoFrameBufferSize
        printf '666666\n' > $U/streaming/mjpeg/m/1920_1080p/dwFrameInterval

        rm -f $U/streaming/class/fs/h $U/streaming/class/hs/h $U/streaming/class/ss/h
        rm -f $U/streaming/header/h/f1 $U/streaming/header/h/f $U/streaming/header/h/m
        ln -s $U/streaming/mjpeg/m $U/streaming/header/h/m
        ln -s $U/streaming/header/h $U/streaming/class/fs/h
        ln -s $U/streaming/header/h $U/streaming/class/hs/h
        ln -s $U/streaming/header/h $U/streaming/class/ss/h

        ln -s $U $C/f1
        echo 21500000.usb > $G/UDC
        touch /userdata/uvc-webcam.on
        log "UDC=$(cat $G/UDC) state=$(cat /sys/class/udc/21500000.usb/state) name=$(cat $U/device_name)"
}

case "$1" in
start)
        ifconfig lo up
        busybox telnetd -l /bin/sh -p 2323 2>/dev/null
        uvc_rk &
        ;;
stop|restart|reload)
        echo "$0: live UDC stop disabled"
        ;;
*)
        echo "Usage: $0 {start}"
        ;;
esac
exit 0
